---
name: "narendranath-check"

x-type: "hlfv1"

description: "MY Network"

version: "1.0"
channels:
  # name of the channel
  private1:
    orderers:
      - orderer1
    # Required. list of peers from participating orgs
    peers:
      peer0_org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org1:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0_org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org2:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

  # name of the channel
  public:
    orderers:
      - orderer1
    # Required. list of peers from participating orgs
    peers:
      peer0_org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org1:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0_org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org2:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0_org3:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org3:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
    chaincodes:
      - mycc:v0

# list of participating organizations in this network
organizations:
  org2:
    mspid: org2MSP
    peers:
      - peer0_org2
      - peer1_org2
    certificateAuthorities:
      - ca_org2
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org2/users/Admin@org2/msp/keystore/0fb54574114f0a46b0a010c2d3c8ae9d37ffb814467c2b8713e334aa66ecfb8a_sk
    signedCert:
      path: crypto-config/peerOrganizations/org2/users/Admin@org2/msp/signcerts/Admin@org2-cert.pem

orderers:
  orderer1:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer1
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: crypto-config/ordererOrganizations/orderer/orderers/orderer1.orderer/tls/ca.crt
peers:
  peer0_org2:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    grpcOptions:
      ssl-target-name-override: peer0_org2
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2/peers/peer0.org2/tls/ca.crt

  peer1_org2:
    url: grpcs://localhost:10051
    eventUrl: grpcs://localhost:10053
    grpcOptions:
      ssl-target-name-override: peer1_org2
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2/peers/peer1.org2/tls/ca.crt

 certificateAuthorities:
  ca_org2:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2/ca/ca.org2-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca_org2
