---
name: "narendranath-check"

x-type: "hlfv1"

description: "MY Network"

version: "1.0"
channels:
  # name of the channel
  private2:
    orderers:
      - orderer2
    # Required. list of peers from participating orgs
    peers:
      peer0_org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org1:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0_org3:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org3:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

  # name of the channel
  public:
    orderers:
      - orderer2
    # Required. list of peers from participating orgs
    peers:
      peer0_org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org1:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0_org2:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org2:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0_org3:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1_org3:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
    chaincodes:
      - mycc:v0

# list of participating organizations in this network
organizations:
  org3:
    mspid: org3MSP
    peers:
      - peer0_org3
      - peer1_org3
    certificateAuthorities:
      - ca_org3
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org3/users/Admin@org3/msp/keystore/3f3a2a4441c50ef74b595147a215119775d2d8a67e57603d629f0101f52d099b_sk
    signedCert:
      path: crypto-config/peerOrganizations/org3/users/Admin@org3/msp/signcerts/Admin@org3-cert.pem

orderers:
  orderer2:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer2
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: crypto-config/ordererOrganizations/orderer/orderers/orderer2.orderer/tls/ca.crt
peers:
  peer0_org3:
    url: grpcs://localhost:11051
    eventUrl: grpcs://localhost:11053
    grpcOptions:
      ssl-target-name-override: peer0_org3
    tlsCACerts:
      path: crypto-config/peerOrganizations/org3/peers/peer0.org3/tls/ca.crt

  peer1_org3:
    url: grpcs://localhost:12051
    eventUrl: grpcs://localhost:12053
    grpcOptions:
      ssl-target-name-override: peer1_org3
    tlsCACerts:
      path: crypto-config/peerOrganizations/org3/peers/peer1.org3/tls/ca.crt

 certificateAuthorities:
  ca_org3:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org3/ca/ca.org3-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca_org3
